### ISSUE TITLE
Facing an error in model inference using provided example

### ISSUE THREAD

**Issue by Rajat060399** [laihuiyuan/mFLAG#1]
>>inp_ids = tokenizer.encode("<hyperbole> I am not happy that he urged me to finish all the hardest tasks in the world", return_tensors="pt")
>>fig_ids = tokenizer.encode("<sarcasm>", add_special_tokens=False, return_tensors="pt")
>>outs = model.generate(input_ids=inp_ids[:, 1:], fig_ids=fig_ids, forced_bos_token_id=fig_ids.item(), num_beams=5, max_length=60,)
>>text = tokenizer.decode(outs[0, 2:].tolist(), skip_special_tokens=True, clean_up_tokenization_spaces=False)

_______________________________________________________________________________________________________________________________________________
AttributeError                            Traceback (most recent call last)
~\AppData\Local\Temp\ipykernel_32792\2188357501.py in <module>
      1 inp_ids = tokenizer.encode("<hyperbole> I am not happy that he urged me to finish all the hardest tasks in the world", return_tensors="pt")
      2 fig_ids = tokenizer.encode("<sarcasm>", add_special_tokens=False, return_tensors="pt")
----> 3 outs = model.generate(input_ids=inp_ids[:, 1:], fig_ids=fig_ids, forced_bos_token_id=fig_ids.item(), num_beams=5, max_length=60,)
      4 text = tokenizer.decode(outs[0, 2:].tolist(), skip_special_tokens=True, clean_up_tokenization_spaces=False)

~\.conda\envs\transformers\lib\site-packages\torch\autograd\grad_mode.py in decorate_context(*args, **kwargs)
     26         def decorate_context(*args, **kwargs):
     27             with self.__class__():
---> 28                 return func(*args, **kwargs)
     29         return cast(F, decorate_context)
     30 

~\.conda\envs\transformers\lib\site-packages\transformers\generation_utils.py in generate(self, inputs, max_length, min_length, do_sample, early_stopping, num_beams, temperature, penalty_alpha, top_k, top_p, typical_p, repetition_penalty, bad_words_ids, force_words_ids, bos_token_id, pad_token_id, eos_token_id, length_penalty, no_repeat_ngram_size, encoder_no_repeat_ngram_size, num_return_sequences, max_time, max_new_tokens, decoder_start_token_id, use_cache, num_beam_groups, diversity_penalty, prefix_allowed_tokens_fn, logits_processor, renormalize_logits, stopping_criteria, constraints, output_attentions, output_hidden_states, output_scores, return_dict_in_generate, forced_bos_token_id, forced_eos_token_id, remove_invalid_values, synced_gpus, exponential_decay_length_penalty, suppress_tokens, begin_suppress_tokens, forced_decoder_ids, **model_kwargs)
   1338             # and added to `model_kwargs`
   1339             model_kwargs = self._prepare_encoder_decoder_kwargs_for_generation(
-> 1340                 inputs_tensor, model_kwargs, model_input_name
   1341             )
   1342 

~\.conda\envs\transformers\lib\site-packages\transformers\generation_utils.py in _prepare_encoder_decoder_kwargs_for_generation(self, inputs_tensor, model_kwargs, model_input_name)
    581         encoder_kwargs["return_dict"] = True
    582         encoder_kwargs[model_input_name] = inputs_tensor
--> 583         model_kwargs["encoder_outputs"]: ModelOutput = encoder(**encoder_kwargs)
    584 
    585         return model_kwargs

~\.conda\envs\transformers\lib\site-packages\torch\nn\modules\module.py in _call_impl(self, *input, **kwargs)
   1100         if not (self._backward_hooks or self._forward_hooks or self._forward_pre_hooks or _global_backward_hooks
   1101                 or _global_forward_hooks or _global_forward_pre_hooks):
-> 1102             return forward_call(*input, **kwargs)
   1103         # Do not call functions when jit is used
   1104         full_backward_hooks, non_full_backward_hooks = [], []

~\Desktop\DS_Team_Tasks\NLP\mFLAG\model.py in forward(self, input_ids, attention_mask, fig_ids, head_mask, inputs_embeds, output_attentions, output_hidden_states, return_dict)
    228             inputs_embeds = self.embed_tokens(input_ids) * self.embed_scale
    229 
--> 230         embed_pos = self.embed_positions(input_shape)
    231 
    232         hidden_states = inputs_embeds + embed_pos

~\.conda\envs\transformers\lib\site-packages\torch\nn\modules\module.py in _call_impl(self, *input, **kwargs)
   1100         if not (self._backward_hooks or self._forward_hooks or self._forward_pre_hooks or _global_backward_hooks
   1101                 or _global_forward_hooks or _global_forward_pre_hooks):
-> 1102             return forward_call(*input, **kwargs)
   1103         # Do not call functions when jit is used
   1104         full_backward_hooks, non_full_backward_hooks = [], []

~\.conda\envs\transformers\lib\site-packages\transformers\models\bart\modeling_bart.py in forward(self, input_ids, past_key_values_length)
    132         """`input_ids' shape is expected to be [bsz x seqlen]."""
    133 
--> 134         bsz, seq_len = input_ids.shape[:2]
    135         positions = torch.arange(
    136             past_key_values_length, past_key_values_length + seq_len, dtype=torch.long, device=self.weight.device

AttributeError: 'torch.Size' object has no attribute 'shape'

**Comment by laihuiyuan** [comment]
Hi! The target figurative token is missing in the second line of code you used. As shown in the example, you should include one token like \<hyperbole\>, \<idiom\>, \<sarcasm\>, \<metaphor\>, or \<simile\>.
