### ISSUE TITLE
about evaluation

### ISSUE THREAD

**Issue by cschy** [laihuiyuan/mFLAG#3]
root@DESKTOP-Q3VVK87:/home/cschy/mflag_test# perl multi-bleu.perl test_hyperbole.1 < l2hyperbole.txt
BLEU = 51.47, 68.7/56.4/47.8/40.2 (BP=0.985, ratio=0.985, hyp_len=1332, ref_len=1352)

when I use multi-bleu.perl to calculate bleu, I find the result is lower than your paper given(the same goes for idiom, sarcasm, idiom and simile). l2hyperbole.txt is created by the output of your checkpoint. Did you do anything extra with the output file? Any help would be appreciated. Below is my generated code:

```from model import MultiFigurativeGeneration
from tokenization_mflag import MFlagTokenizerFast
tokenizer = MFlagTokenizerFast.from_pretrained('laihuiyuan/mFLAG', cache_dir='author')
model = MultiFigurativeGeneration.from_pretrained('laihuiyuan/mFLAG', cache_dir='author')
with open('./data/MultiFG/test_hyperbole.0', 'r') as f, open('./data/outputs/l2hyperbole.txt', 'w') as fw:
    lines = f.readlines()
    for i in lines:
        inp_ids = tokenizer.encode(
            "<literal>" + i.strip(), return_tensors="pt")
        fig_ids = tokenizer.encode("<hyperbole>", add_special_tokens=False, return_tensors="pt")
        outs = model.generate(input_ids=inp_ids[:, 1:], fig_ids=fig_ids, forced_bos_token_id=fig_ids.item(), num_beams=5,
                              max_length=60, )
        text = tokenizer.decode(outs[0, 2:].tolist(), skip_special_tokens=True, clean_up_tokenization_spaces=False)
        print(text)
        fw.write(text + '\n')

**Comment by laihuiyuan** [comment]
Hi! Did you perform tokenization (both outputs and references) before calculating the BLEU score?

**Comment by cschy** [comment]
> Hi! Did you perform tokenization (both outputs and references) before calculating the BLEU score?

Sorry, my bad. Is tokenization a word segmentation operation rather than furtherly converting sentences into a dictionary index (or tensor)? By the way, could you tell me which function to use? Thank you very much!

**Comment by laihuiyuan** [comment]
Yes, it is a word segmentation, I used nltk.word_tokenize.

**Comment by cschy** [comment]
> Yes, it is a word segmentation, I used nltk.word_tokenize.

In fact, you have already given tokenizer.py, thank you.

**Comment by cschy** [comment]
root@DESKTOP-Q3VVK87:/home/cschy/mflag# perl multi-bleu.perl hyperbole-ref.txt < hyperbole-gen.txt
BLEU = 55.68, 75.0/60.3/51.7/44.6 (BP=0.980, ratio=0.980, hyp_len=1553, ref_len=1585)
root@DESKTOP-Q3VVK87:/home/cschy/mflag# perl multi-bleu.perl idiom-gen.txt < idiom-ref.txt
BLEU = 70.60, 81.8/73.1/67.3/61.7 (BP=1.000, ratio=1.028, hyp_len=16743, ref_len=16293)
root@DESKTOP-Q3VVK87:/home/cschy/mflag# perl multi-bleu.perl sarcasm-ref.txt < sarcasm-gen.txt
BLEU = 46.98, 71.9/58.5/53.8/51.1 (BP=0.806, ratio=0.822, hyp_len=18734, ref_len=22780)
root@DESKTOP-Q3VVK87:/home/cschy/mflag# perl multi-bleu.perl metaphor-ref.txt < metaphor-gen.txt
BLEU = 50.22, 77.8/58.5/44.5/31.4 (BP=1.000, ratio=1.033, hyp_len=1274, ref_len=1233)
root@DESKTOP-Q3VVK87:/home/cschy/mflag# perl multi-bleu.perl simile-ref.txt < simile-gen.txt
BLEU = 56.21, 81.6/68.9/65.0/60.7 (BP=0.819, ratio=0.834, hyp_len=1950, ref_len=2339)

Just hyperbole is in accordance with yours, the rest is lower than your result. I converted them all to lowercase. Is it because the rest of the figurative text is not converted to lowercase?

**Comment by cschy** [comment]
```
root@DESKTOP-Q3VVK87:/home/cschy/mflag/l2f# perl multi-bleu.perl hyperbole/ref_lower.txt < hyperbole/hyp_lower.txt
BLEU = 55.68, 75.0/60.3/51.7/44.6 (BP=0.980, ratio=0.980, hyp_len=1553, ref_len=1585)
root@DESKTOP-Q3VVK87:/home/cschy/mflag/l2f# perl multi-bleu.perl idiom/ref_lower.txt < idiom/hyp_lower.txt
BLEU = 76.16, 86.7/79.5/74.5/69.8 (BP=0.984, ratio=0.984, hyp_len=16477, ref_len=16743)
root@DESKTOP-Q3VVK87:/home/cschy/mflag/l2f# perl multi-bleu.perl sarcasm/ref_lower.txt < sarcasm/hyp_lower.txt
BLEU = 49.16, 76.0/63.7/59.4/57.1 (BP=0.772, ratio=0.795, hyp_len=18105, ref_len=22780)
root@DESKTOP-Q3VVK87:/home/cschy/mflag/l2f# perl multi-bleu.perl metaphor/ref_lower.txt < metaphor/hyp_lower.txt
BLEU = 62.89, 87.4/71.7/57.9/45.1 (BP=0.989, ratio=0.989, hyp_len=1219, ref_len=1233)
```
it's ok, but simile can't get 74.5, not only test_simile.1 but also test_simile.1.1. The suffix 'lower' means lowercase:

```
root@DESKTOP-Q3VVK87:/home/cschy/mflag/l2f# perl multi-bleu.perl simile/ref_lower.txt < simile/hyp_lower.txt
BLEU = 66.27, 85.5/73.8/70.5/67.7 (BP=0.894, ratio=0.900, hyp_len=2104, ref_len=2339)
root@DESKTOP-Q3VVK87:/home/cschy/mflag/l2f# perl multi-bleu.perl simile/ref.txt < simile/hyp.txt
BLEU = 66.27, 85.5/73.8/70.5/67.7 (BP=0.894, ratio=0.900, hyp_len=2104, ref_len=2339)
root@DESKTOP-Q3VVK87:/home/cschy/mflag/l2f# perl multi-bleu.perl simile/ref1.1.txt < simile/hyp1.1.txt
BLEU = 66.77, 77.8/67.1/63.4/60.0 (BP=1.000, ratio=1.003, hyp_len=2234, ref_len=2227)
root@DESKTOP-Q3VVK87:/home/cschy/mflag/l2f# perl multi-bleu.perl simile/ref1.1_lower.txt < simile/hyp1.1_lower.txt
BLEU = 66.77, 77.8/67.1/63.4/60.0 (BP=1.000, ratio=1.003, hyp_len=2234, ref_len=2227)
```

**Comment by laihuiyuan** [comment]
We did not lowercase the output (reference). There are two references for each source sentence in the simile dataset,  so we run the script to compute the multi-reference score.
